---
- name: Deploying Prometheus and Grafana
  hosts: ec2
  become: yes
  tasks:
    - name: Add Prometheus Helm repo
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Add Grafana Helm repo
      command: helm repo add grafana https://grafana.github.io/helm-charts

    - name: Update Helm repos
      command: helm repo update

    - name: Install Prometheus
      command: helm install prometheus prometheus-community/prometheus

    - name: Install Grafana
      command: helm install grafana grafana/grafana

    - name: Expose Prometheus service to NodePort
      command: kubectl expose service prometheus-server --type=NodePort --target-port=9090 --name=prometheus-server-ext

    - name: Expose Grafana service to NodePort
      command: kubectl expose service grafana --type=NodePort --target-port=3000 --name=grafana-ext
      
    - name: Print Prometheus external endpoint
      command: kubectl get service prometheus-server-ext -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
      register: prometheus_endpoint

    - name: Print Grafana external endpoint
      command: kubectl get service grafana-ext -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
      register: grafana_endpoint

    - name: Display Prometheus external endpoint
      debug:
        msg: "Prometheus external endpoint: {{ prometheus_endpoint.stdout }}"

    - name: Display Grafana external endpoint
      debug:
        msg: "Grafana external endpoint: {{ grafana_endpoint.stdout }}"

