---
- name: Deploying Prometheus and Grafana
  hosts: ec2
  become: yes
  tasks:
    - name: Add Prometheus Helm repo
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Add Grafana Helm repo
      command: helm repo add grafana https://grafana.github.io/helm-charts

    - name: Update Helm repos
      command: helm repo update

    - name: Install Prometheus
      command: helm install prometheus prometheus-community/prometheus

    - name: Install Grafana
      command: helm install grafana grafana/grafana

    - name: Expose Prometheus service to NodePort
      command: kubectl expose service prometheus-server --type=NodePort --target-port=9090 --name=prometheus-server-ext

    - name: Expose Grafana service to NodePort
      command: kubectl expose service grafana --type=NodePort --target-port=3000 --name=grafana-ext
